### ISSUE TITLE
Finale sachen

### ISSUE THREAD

**Issue by chegerland** [F-Praktikum-Bros/Praktikum_TCSPC#30]
- Durchlesen und Fehler korrigieren (Grammatik und schauen, dass alle Abb. ZAHL bzw. Tabelle ZAHL weg sind bzw. richtig nummeriert sind)
- über Fehler reden!

**Comment by mp1995a** [comment]
OK, nach der Fehlerdiskussion les ich Korrektur; fragt sich nur inwiefern sich die Fehler"diskussion" auf mehr als einen Satz erweitern lässt?
